#!/usr/bin/env bash
##
# Generated by Cloudera Manager and should not be modified directly
##

export SPARK_HOME={{SPARK_HOME}}
export STANDALONE_SPARK_MASTER_HOST={{MASTER_IP}}
export SPARK_MASTER_PORT={{MASTER_PORT}}
export DEFAULT_HADOOP_HOME={{HADOOP_HOME}}

### Path of Spark assembly jar in HDFS
export SPARK_JAR_HDFS_PATH={{SPARK_JAR_HDFS_PATH}}

### Let's run everything with JVM runtime, instead of Scala
export SPARK_LAUNCH_WITH_SCALA=0
export SPARK_LIBRARY_PATH=${SPARK_HOME}/lib
export SCALA_LIBRARY_PATH=${SPARK_HOME}/lib
export SPARK_MASTER_IP=$STANDALONE_SPARK_MASTER_HOST

export HADOOP_HOME=${HADOOP_HOME:-$DEFAULT_HADOOP_HOME}

if [ -n "$HADOOP_HOME" ]; then
  export SPARK_LIBRARY_PATH=$SPARK_LIBRARY_PATH:${HADOOP_HOME}/lib/native
fi

export HADOOP_CONF_DIR=/etc/hadoop/conf
